### PR TITLE
Add methods to handle month change and properties for the arrows color

### PR DESCRIPTION
**Pull request by luccasclezar**
When I was going to use the library I found very strange that it didn't have any method to change months programmatically. Then I was digging into the code and I found that this could be achieved by changing the StartDate. So I am doing this PR to make this a little more easy and intuitive.
And as I was already doing this, I added two properties to change the color of the arrows. :)

### CODE REVIEW

**Comment by KRA2008** [comment]
But TitleLeftArrow and TitleRightArrow are already publicly visible properties. Is it really that helpful to expose TitleLeftArrow.TextColor as a standalone property?

**Comment by KRA2008** [comment]
The comment you can't see is from me. I made the comment and removed it because I thought better of it and wondered if there was a better way to do things that I would go and look at. The important part of #19 is that the properties be bindable. I wanted that so I could set the color in my XAML. Without those parts, I don't see the benefit. Similar reasoning for #18.

**Comment by luccasclezar** [comment]
Sorry, didn't see the name lol.

I forgot XAML, I'll add bindable properties to the commit :)

**Comment by luccasclezar** [comment]
Did it :)

And thank you for reminding me of XAML

**Pull request merged**
